Split transaction
vibhaa/lnd pull request #5
Opened 2018-11-30 22:07 UTC by yangl1996

will fill in details soon

2018-12-02 23:26 UTC, vibhaa commented on routing/router.go
> +// have been attempted and resulted in a failed payment. If the payment
Does this attempt all routes or just the shortest one? So even if that one fails it will return failed payment right?

2018-12-02 23:29 UTC, vibhaa commented on routing/router_test.go
> +	// to luo ji for 1000 satoshis, with a maximum of 1000 satoshis in fees.
it says "no fee limit" here though. Is there a fee then? Does the comment need some editing.

2018-12-02 23:30 UTC, vibhaa commented on routing/router_test.go
> +	ctx, cleanUp, err := createTestCtxFromFile(startingBlockHeight, basicGraphFilePath)
What does the topology look like for this? Just for context?

2018-12-02 23:35 UTC, vibhaa commented on lnrpc/rpc.proto
> +    int32 spiderAlgo = 9;
Can you please add a comment here like the above fields explaining what this parameter is?

2018-12-02 23:37 UTC, vibhaa commented on lnd_test.go
> +func testSpiderShortestPath(net *lntest.NetworkHarness, t *harnessTest) {
Can you add a comment here detailing what this test is about similar to all the above tests?

2018-12-02 23:39 UTC, vibhaa commented on lnd_test.go
> +	networkChans = append(networkChans, chanPointn1n2)
Can you also add a comment for every block here as to what channel its opening and what hash its collecting? Just a line or two would be great for like n1n2 and then n2n3 and so on.

2018-12-02 23:42 UTC, vibhaa commented on lnd_test.go
Can you add a comment saying "receive responses" or something brief?

2018-12-02 23:45 UTC, vibhaa commented on lnd_test.go
> +	feeRate := int64(1)
can you add a comment explaining these two fields? In particular, what is feeRate?

2018-12-02 23:45 UTC, vibhaa commented on lnd_test.go
> +	graphSubs := make([]graphSubscription, numNodes)
What is this graphSubscription about?

2018-12-02 23:47 UTC, vibhaa commented on lnd_test.go
> +	graphSubs := make([]graphSubscription, numNodes)
Can you add some more comments on what exactly is happening here? Did you add these graphNotifications? If so, what are they/where are they? If not, can you expand on how you're using them?

2018-12-02 23:48 UTC, vibhaa commented on lnd_test.go
> +
Can you add a brief comment on what exactly is happening here? In particular, why do we need to "update" the policy?

2018-12-02 23:48 UTC, vibhaa commented on lnd_test.go
> +
Similarly, can you add a comment saying "Collecting statistics - success rate and volume or something like that?"

2018-12-02 23:50 UTC, vibhaa commented on lnd_test.go
> +	var tranwg sync.WaitGroup
Can you add a comment to explain what these wait groups are doing and how they are relevant below?

2018-12-02 23:52 UTC, vibhaa commented on routing/missioncontrol.go
> +	pruneView := graphPruneView{}
What exactly is this change doing? Just curious

2018-12-02 23:54 UTC, vibhaa commented on lnd_test.go
> +		expectedMessages[i * 2] = expectedChanUpdate{
Same question: What exactly is happening here?

2018-12-02 23:54 UTC, vibhaa commented on chainregistry.go
> +	defaultBitcoinMinHTLCMSat   = lnwire.MilliSatoshi(0)
This is okay for now, but can we add an issue to track this? We might want to change it back at some point (so as to not affect LND)

2018-12-02 23:56 UTC, vibhaa commented on lnd_test.go
> +	var totFailed uint64 = 0
Please add another comment here saying "aggregating per intent or demand pair success rates.

2018-12-03 00:01 UTC, vibhaa commented on lnrpc/rpc.swagger.json
> +          "format": "int32"
I would add a description here too, to clarify what this is about.

2018-12-03 00:01 UTC, vibhaa commented on lntest/harness.go
> +func (n *NetworkHarness) NewNode(name string, extraArgs []string, delay ...int) (*HarnessNode, error) {
Can you add the delay explanation to the comments also?

2018-12-03 00:02 UTC, vibhaa commented on lntest/node.go
> +	Delay int
Can you add a comment explaining what this delay is?

2018-12-03 00:03 UTC, vibhaa commented on routing/missioncontrol.go
> +	// Taking into account this prune view, we'll attempt to locate a path
"locate the shortest path"

2018-12-03 02:12 UTC, vibhaa commented on lnd_test.go
> +	for i := 0; i < numPayIntents; i++ {
Any chance you can refactor this code and give all the goroutines names? Its just really hard to follow the whole 3 layers of goroutines. I get the flow - but might help if there were some descriptive names/self contained functions.

2018-12-03 02:13 UTC, vibhaa commented on lnrpc/rpc.pb.go
> +	SpiderAlgo int32     `protobuf:"varint,9,opt,name=spiderAlgo" json:"spiderAlgo,omitempty"`
Please add a comment

2018-12-03 02:13 UTC, vibhaa commented on lnrpc/rpc.pb.go
> +func (m *SendRequest) GetSpiderAlgo() int32 {
Please add a single line comment atleast here

2018-12-03 02:14 UTC, vibhaa commented on lntest/node.go
> +	// we first apply delay config to the node
maybe mention using "tcconfig we create a new delay shell" or whatever the right phrase is?

2018-12-03 02:16 UTC, vibhaa commented on routing/missioncontrol.go
> +func (p *paymentSession) RequestShortestPath(payment *LightningPayment,
Comment for the function please?

2018-12-03 02:26 UTC, vibhaa commented on routing/router.go
> +const (
What are these constants for? Can we add some comments?

2018-12-03 02:35 UTC, vibhaa commented on rpcserver.go
> +	spiderAlgo int
Comment will be helpful

2018-12-03 02:37 UTC, vibhaa commented
Most of these are minor nits/addition on comments. There's only one place in the testing code where I felt a little code refactoring could be helpful. Otherwise looks good

2018-12-03 02:39 UTC, vibhaa requested changes
I think most of these are fine except for needing a few more comments. My only issue was with some code in the tests that I felt could be refactored a little. Other than that would recommend fixing the 3 things you yourself mentioned also. (Readme/removing it from itest would be very helpful) and please do run make itest before merging.

2018-12-03 17:27 UTC, yangl1996 commented
Thanks for the review! I've added most of the requested comments. I'll refactor the `lnd_test` test case  later today, and fix the itest tomorrow - it currently fails, maybe because I changed the minHTLC and minFees values.

BTW, I marked requests that I have fixed as resolved, so it is easier to track which requests have not been fixed. Feel free to reopen :)

2018-12-12 18:16 UTC, merged